name: AI Release Notes Action
description: |
  Publish a release with current PR and generates a better-written (Human readable) changelog text.
author: "Diego Bugs"
branding:
  icon: "cpu"
  color: "blue"

inputs:
  language:
    description: "The language of the output."
    required: true
    default: "en"
  openai-api-key:
    description: "The OpenAI API key."
    required: true
  token:
    description: "The GitHub token."
    required: false
  version:
    description: "The version of the release."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"
